// <auto-generated />
using System;
using CRUDEFCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD_EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706021311_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CRUDEFCore.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CRUDEFCore.Models.Equipment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCalibrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("EmployeeEquipment", b =>
                {
                    b.Property<int>("Employeesid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentsListID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Employeesid", "EquipmentsListID");

                    b.HasIndex("EquipmentsListID");

                    b.ToTable("EmployeeEquipment");
                });

            modelBuilder.Entity("EmployeeEquipment", b =>
                {
                    b.HasOne("CRUDEFCore.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("Employeesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUDEFCore.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentsListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
